### ISSUE TITLE
MA-4 (2): Document Nonlocal Maintenance

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#1000]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ma/#MA-4%20(2)

MA-4 (2): Document Nonlocal Maintenance

“The organization documents in the security plan for the information system, the policies and procedures for the establishment and use of nonlocal maintenance and diagnostic connections.”

**Comment by redhatrises** [comment]
This control was evaluated as not applicable. See #1066
