### ISSUE TITLE
MA-4 (5): Approvals And Notifications

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#1003]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ma/#MA-4%20(5)

MA-4 (5): Approvals And Notifications

The organization: (5)(a). Requires the approval of each nonlocal maintenance session by [Assignment: organization-defined personnel or roles]; and (5)(b). Notifies [Assignment: organization-defined personnel or roles] of the date and time of planned nonlocal maintenance.

**Comment by shawndwells** [comment]
Not applicable to CoreOS, however, the content could be enhanced by including language around CoreOS assumption that all/most maintenance is nonlocal

**Comment by redhatrises** [comment]
This control was evaluated as not applicable. See #1066
