### ISSUE TITLE
MA-6: Timely Maintenance

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#1010]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ma/#MA-6

MA-6: Timely Maintenance

“The organization obtains maintenance support and/or spare parts for [Assignment: organization-defined information system components] within [Assignment: organization-defined time period] of failure.”

**Comment by redhatrises** [comment]
This control was evaluated as not applicable. See #1066
