### ISSUE TITLE
MA-6 (1): Preventive Maintenance

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#1011]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ma/#MA-6%20(1)

MA-6 (1): Preventive Maintenance

“The organization performs preventive maintenance on [Assignment: organization-defined information system components] at [Assignment: organization-defined time intervals].”

**Comment by shawndwells** [comment]
Could create a doc about how preventive maintenance is planned to occur on CoreOS

**Comment by redhatrises** [comment]
This control was evaluated as not applicable. See #1066
