### ISSUE TITLE
MA-6 (2): Predictive Maintenance

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#1012]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ma/#MA-6%20(2)

MA-6 (2): Predictive Maintenance

“The organization performs predictive maintenance on [Assignment: organization-defined information system components] at [Assignment: organization-defined time intervals].”

**Comment by redhatrises** [comment]
This control was evaluated as not applicable. See #1066
