### ISSUE TITLE
MA-6 (3): Automated Support For Predictive Maintenance

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#1013]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ma/#MA-6%20(3)

MA-6 (3): Automated Support For Predictive Maintenance

“The organization employs automated mechanisms to transfer predictive maintenance data to a computerized maintenance management system.”

**Comment by shawndwells** [comment]
Insights?

**Comment by redhatrises** [comment]
This control was evaluated as not applicable. See #1066
