### ISSUE TITLE
Openshift 4 on CoreOS FISMA compliance

### ISSUE THREAD

**Issue by dhartford** [ComplianceAsCode/redhat#720]
Hi Team,
Is there any starting work for the Openshift Container Platform 4 versus only OCP 3? 

With the shift to CoreOS under the covers, there is a lot of fear/uncertainty/doubt around if OCP4 would be as secure (compliance-wise) as OCP3.

**Comment by shawndwells** [comment]
On 7/26/19 10:28 AM, Darren Hartford wrote:
>
> Hi Team,
> Is there any starting work for the Openshift Container Platform 4 
> versus only OCP 3?
>
> With the shift to CoreOS under the covers, there is a lot of 
> fear/uncertainty/doubt around if OCP4 would be as secure 
> (compliance-wise) as OCP3.
>
Yes. There's broad knowledge that CoreOS is not Government ready. Most 
likely not ready until OCP 4.2 or 4.3. Will send some links to where 
we're tracking that work later today.

**Comment by shawndwells** [comment]
@dhartford work in progress control mappings are being created for CoreOS now. Current status:

http://atopathways.redhatgov.io/product-documents/coreos4/
