### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by anoncam** [ComplianceAsCode/redhat#761]
pong

**Comment by shawndwells** [comment]
When does a ping pong player go to sleep?

**Comment by anoncam** [comment]
when the player tires.

**Comment by shawndwells** [comment]
> when the player tires.

Around tenish!

**Comment by anoncam** [comment]
What's the easiest implementation of automated sec checks?  it's a PaC approach no?  The time gained on not refactoring must be worth the thought at the onset.  Or no?
