### ISSUE TITLE
Automatic builds for OSD FedRAMP microsite

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#782]
@redhatrises Could the OpenShift infrastructure be setup to automatically build upon merged pull requests to his repo?

**Comment by redhatrises** [comment]
@shawndwells https://docs.openshift.com/online/dev_guide/builds/triggering_builds.html#github-webhooks so you know how to setup in the future.

**Comment by redhatrises** [comment]
Should be fixed now.
