### ISSUE TITLE
CM-3 (1): Automated Document / Notification / Prohibition Of Changes

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#890]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cm/#CM-3%20(1)

CM-3 (1): Automated Document / Notification / Prohibition Of Changes

The organization employs automated mechanisms to: (1)(a). Document proposed changes to the information system; (1)(b). Notify [Assignment: organized-defined approval authorities] of proposed changes to the information system and request change approval; (1)(c). Highlight proposed changes to the information system that have not been approved or disapproved by [Assignment: organization-defined time period]; (1)(d). Prohibit changes to the information system until designated approvals are received; (1)(e). Document all changes to the information system; and (1)(f). Notify [Assignment: organization-defined personnel] when approved changes to the information system are completed.

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1082
