### ISSUE TITLE
CM-3 (2): Test / Validate / Document Changes

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#891]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cm/#CM-3%20(2)

CM-3 (2): Test / Validate / Document Changes

“The organization tests, validates, and documents changes to the information system before implementing the changes on the operational system.”

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1082
