### ISSUE TITLE
CM-5 (2): Review System Changes

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#898]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cm/#CM-5%20(2)

CM-5 (2): Review System Changes

“The organization reviews information system changes [Assignment: organization-defined frequency] and [Assignment: organization-defined circumstances] to determine whether unauthorized changes have occurred.”

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1082
