### ISSUE TITLE
CM-6 (2): Respond To Unauthorized Changes

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#905]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cm/#CM-6%20(2)

CM-6 (2): Respond To Unauthorized Changes

“The organization employs [Assignment: organization-defined security safeguards] to respond to unauthorized changes to [Assignment: organization-defined configuration settings].”

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1082
