### ISSUE TITLE
CM-9: Configuration Management Plan

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#918]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cm/#CM-9

CM-9: Configuration Management Plan

The organization develops, documents, and implements a configuration management plan for the information system that: a. Addresses roles, responsibilities, and configuration management processes and procedures; b. Establishes a process for identifying configuration items throughout the system development life cycle and for managing the configuration of the configuration items; c. Defines the configuration items for the information system and places the configuration items under configuration management; and d. Protects the configuration management plan from unauthorized disclosure and modification.

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1082
