### ISSUE TITLE
CM-11: User-Installed Software

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#920]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cm/#CM-11

CM-11: User-Installed Software

The organization: a. Establishes [Assignment: organization-defined policies] governing the installation of software by users; b. Enforces software installation policies through [Assignment: organization-defined methods]; and c. Monitors policy compliance at [Assignment: organization-defined frequency].

**Comment by mrguitar** [comment]
@shawndwells why is this an issue? User installed software isn't allowed or supported. What is the ask here?

**Comment by shawndwells** [comment]
@mrguitar What happens if a user ssh's into CoreOS and runs ``sudo rpm -ivh <rpm>`` or ``sudo yum install <package>``? Possible control response would be creating documentation around how to prevent these scenarios. 

Outside the standard RPM install, what if someone wants add packages into their build (e.g. agents or antivirus). Where do we document the appropriate way to do that?

**Comment by mrguitar** [comment]
@shawndwells /usr is mounted read-only. 'yum' is not part of the system. RHCOS, like it's predecessor Container Linux, is built to run containers and additional software must be run as a container. This is in the architecture docs for OpenShift.

**Comment by shawndwells** [comment]
@mrguitar Other CoreOS docs outline how to install software, e.g. https://coreos.com/os/docs/latest/install-debugging-tools.html and https://coreos.com/matchbox/docs/latest/deployment.html#rpm-based-distro

**Comment by shawndwells** [comment]
p.s. not disagreeing with you. This might be one of those "point to the right docs" examples.

**Comment by mrguitar** [comment]
Container Linux is a gentoo based operating system that is in maintenance mode and close to reaching end of life. Please do not refer to documentation from a different operating system. Red Hat Enterprise Linux CoreOS docs are here: https://docs.openshift.com/container-platform/4.1/architecture/architecture-rhcos.html

We do include toolbox that is an important tool for troubleshooting. Any operating system that can launch a container can perform steps like the ones you linked to.
