### ISSUE TITLE
CM-11 (1): Alerts For Unauthorized Installations

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#921]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cm/#CM-11%20(1)

CM-11 (1): Alerts For Unauthorized Installations

“The information system alerts [Assignment: organization-defined personnel or roles] when the unauthorized installation of software is detected.”

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1082
