### ISSUE TITLE
CP-2 (2): Capacity Planning

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#925]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-2%20(2)

CP-2 (2): Capacity Planning
“The organization conducts capacity planning so that necessary capacity for information processing, telecommunications, and environmental support exists during contingency operations.”

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
