### ISSUE TITLE
CP-2 (6): Alternate Processing / Storage Site

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#926]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-2%20(6)

CP-2 (6): Alternate Processing / Storage Site

“The organization plans for the transfer of essential missions and business functions to alternate processing and/or storage sites with little or no loss of operational continuity and sustains that continuity through information system restoration to primary processing and/or storage sites.”

**Comment by shawndwells** [comment]
Example control response could discuss cluster failover capabilities.

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
