### ISSUE TITLE
CP-2 (8): Identify Critical Assets

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#927]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-2%20(8)

CP-2 (8): Identify Critical Assets

“The organization identifies critical information system assets supporting essential missions and business functions.”

**Comment by shawndwells** [comment]
example: should CoreOS master nodes be considered critical assets (vs worker nodes)

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
