### ISSUE TITLE
CP-3 (1): Simulated Events

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#928]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-3%20(1)

CP-3 (1): Simulated Events

“The organization incorporates simulated events into contingency training to facilitate effective response by personnel in crisis situations.”

**Comment by shawndwells** [comment]
Whitepaper idea: what events should be simulated/practiced for contingency training (for CoreOS/OCP operators)?

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
