### ISSUE TITLE
CP-4 (4): Full Recovery / Reconstitution

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#930]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-4%20(4)

CP-4 (4): Full Recovery / Reconstitution

“The organization includes a full recovery and reconstitution of the information system to a known state as part of contingency plan testing.”

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
