### ISSUE TITLE
CP-6 (2): Recovery Time / Point Objectives

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#931]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-6%20(2)

CP-6 (2): Recovery Time / Point Objectives

“The organization configures the alternate storage site to facilitate recovery operations in accordance with recovery time and recovery point objectives.”

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
