### ISSUE TITLE
CP-7 (4): Preparation For Use

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#933]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-7%20(4)

CP-7 (4): Preparation For Use

“The organization prepares the alternate processing site so that the site is ready to be used as the operational site supporting essential missions and business functions.”

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
