### ISSUE TITLE
CP-9 (5): Transfer To Alternate Storage Site

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#937]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-9%20(5)

CP-9 (5): Transfer To Alternate Storage Site

“The organization transfers information system backup information to the alternate storage site [Assignment: organization-defined time period and transfer rate consistent with the recovery time and recovery point objectives].”

**Comment by shawndwells** [comment]
what, if any, CoreOS data should be backed up? Can QoS be defined for backups?

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
