### ISSUE TITLE
CP-9 (7): Dual Authorization

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#939]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-9%20(7)

CP-9 (7): Dual Authorization

“The organization enforces dual authorization for the deletion or destruction of [Assignment: organization-defined backup information].”

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
