### ISSUE TITLE
CP-10 (2): Transaction Recovery

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#941]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-10%20(2)

CP-10 (2): Transaction Recovery

“The information system implements transaction recovery for systems that are transaction-based.”

**Comment by shawndwells** [comment]
Is this even relevant to CoreOS (guessing not)?

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
