### ISSUE TITLE
CP-10 (4): Restore Within Time Period

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#942]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/cp/#CP-10%20(4)

CP-10 (4): Restore Within Time Period

“The organization provides the capability to restore information system components within [Assignment: organization-defined restoration time-periods] from configuration-controlled and integrity-protected information representing a known, operational state for the components.”

**Comment by redhatrises** [comment]
This control is no longer considered applicable. See #1057
