### ISSUE TITLE
IA-2 (11): Remote Access - Separate Device

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#960]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ia/#IA-2%20(11)

IA-2 (11): Remote Access - Separate Device

“The information system implements multifactor authentication for remote access to privileged and non-privileged accounts such that one of the factors is provided by a device separate from the system gaining access and the device meets [Assignment: organization-defined strength of mechanism requirements].”

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1081
