### ISSUE TITLE
IA-2 (13): Out-Of-Band Authentication

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#962]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ia/#IA-2%20(13)

IA-2 (13): Out-Of-Band Authentication

“The information system implements [Assignment: organization-defined out-of-band authentication] under [Assignment: organization-defined conditions].”

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1081
