### ISSUE TITLE
IA-4: Identifier Management

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#967]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ia/#IA-4

IA-4: Identifier Management

The organization manages information system identifiers by: a. Receiving authorization from [Assignment: organization-defined personnel or roles] to assign an individual, group, role, or device identifier; b. Selecting an identifier that identifies an individual, group, role, or device; c. Assigning the identifier to the intended individual, group, role, or device; d. Preventing reuse of identifiers for [Assignment: organization-defined time period]; and e. Disabling the identifier after [Assignment: organization-defined time period of inactivity].

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1081
