### ISSUE TITLE
IA-4 (4): Identify User Status

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#969]
IA-4 (4): Identify User Status

“The organization manages individual identifiers by uniquely identifying each individual as [Assignment: organization-defined characteristic identifying individual status].”

**Comment by shawndwells** [comment]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ia/#IA-4%20(4)

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1081
