### ISSUE TITLE
IA-5 (5): Change Authenticators Prior To Delivery

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#975]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ia/#IA-5%20(5)

IA-5 (5): Change Authenticators Prior To Delivery

“The organization requires developers/installers of information system components to provide unique authenticators or change default authenticators prior to delivery/installation.”

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1081
