### ISSUE TITLE
IA-5 (6): Protection Of Authenticators

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#976]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ia/#IA-5%20(6)

IA-5 (6): Protection Of Authenticators

“The organization protects authenticators commensurate with the security category of the information to which use of the authenticator permits access.”

**Comment by redhatrises** [comment]
This has been evaluated as not applicable. See #1081
