### ISSUE TITLE
MA-1: System Maintenance Policy And Procedures

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#992]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ma/#MA-1

MA-1: System Maintenance Policy And Procedures

The organization: a. Develops, documents, and disseminates to [Assignment: organization-defined personnel or roles]: 1. A system maintenance policy that addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and 2. Procedures to facilitate the implementation of the system maintenance policy and associated system maintenance controls; and b. Reviews and updates the current: 1. System maintenance policy [Assignment: organization-defined frequency]; and 2. System maintenance procedures [Assignment: organization-defined frequency].

**Comment by shawndwells** [comment]
"Procedures to facilitate the implementation of the system maintenance policy and associated system maintenance controls"

aka how do we update CoreOS?

**Comment by shawndwells** [comment]
(technically MA-1 is not applicable as an organizational control)

**Comment by redhatrises** [comment]
This control was evaluated as not applicable. See #1066
