### ISSUE TITLE
MA-2: Controlled Maintenance

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#993]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ma/#MA-2

MA-2: Controlled Maintenance

The organization: a. Schedules, performs, documents, and reviews records of maintenance and repairs on information system components in accordance with manufacturer or vendor specifications and/or organizational requirements; b. Approves and monitors all maintenance activities, whether performed on site or remotely and whether the equipment is serviced on site or removed to another location; c. Requires that [Assignment: organization-defined personnel or roles] explicitly approve the removal of the information system or system components from organizational facilities for off-site maintenance or repairs; d. Sanitizes equipment to remove all information from associated media prior to removal from organizational facilities for off-site maintenance or repairs; e. Checks all potentially impacted security controls to verify that the controls are still functioning properly following maintenance or repair actions; and f. Includes [Assignment: organization-defined maintenance-related information] in organizational maintenance records.

**Comment by redhatrises** [comment]
This control was evaluated as not applicable. See #1066
