### ISSUE TITLE
MA-3 (1): Inspect Tools

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/redhat#996]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ma/#MA-3%20(1)

MA-3 (1): Inspect Tools

“The organization inspects the maintenance tools carried into a facility by maintenance personnel for improper or unauthorized modifications.”

**Comment by redhatrises** [comment]
This control was evaluated as not applicable. See #1066
